export type Locale = "pl" | "en" | "de";

export const LOCALES: { code: Locale; label: string; short: string; flag: string }[] = [
  { code: "pl", label: "Polski", short: "PL", flag: "🇵🇱" },
  { code: "en", label: "English", short: "EN", flag: "🇬🇧" },
  { code: "de", label: "Deutsch", short: "DE", flag: "🇩🇪" },
];

export type Dict = (typeof content)["pl"];

export const content = {
  pl: {
    meta: {
      title: "Vantix — Strona, lejek, reklamy i strategia wzrostu",
      description:
        "Growth Partner dla firm usługowych. Strona, lejek, reklamy i miesięczna strategia — jeden człowiek odpowiedzialny za cały lejek pozyskiwania klienta.",
    },
    nav: { problem: "Problem", solution: "Rozwiązanie", process: "Proces", pricing: "Wycena", audit: "Audyt", blog: "Blog", menu: "Menu", theme: "Zmień motyw", language: "Język" },
    hero: {
      badge: "Growth Partner dla firm usługowych",
      h1a: "Zapłaciłeś agencji.",
      h1b: "Wyników dalej nie",
      h1c: "masz",
      p: "90% agencji nie ogarnia AI, a kiedy coś nie działa — winny jest zawsze „ktoś inny z zespołu”. U mnie odpowiada jeden człowiek: ja.",
      cta: "Bezpłatny audyt — 15 min",
      ctaNote: "Zero zobowiązań. Konkret w 3 punktach.",
    },
    promise: {
      eyebrow: "Jak pracuję",
      title: "Obietnica procesu, nie obietnica cudu.",
      items: [
        { k: "Cel: 30–60 dni", v: "Tyle zwykle zajmuje uruchomienie strony, lejka i pierwszych kampanii — do pierwszych zapytań." },
        { k: "1 osoba", v: "Jeden kontakt, jedna faktura, jedna odpowiedzialność za wynik. Bez przerzucania się winą." },
        { k: "Zero ryzyka na start", v: "Zaczynamy od bezpłatnego audytu. Zakres i model rozliczenia ustalamy dopiero po nim." },
      ],
    },
    story: {
      eyebrow: "Skąd to się wzięło",
      title: "Zanim zacząłem robić lejki, pracowałem fizycznie.",
      p1: "Montaże, instalacje, realna robota — nie PowerPoint. Pracowałem u ludzi, którzy mieli pełne ręce roboty w jednym miesiącu i pustą kolejkę w kolejnym, bo pozyskiwanie klientów opierało się wyłącznie na polecaniu.",
      p2a: "Ten sam problem widziałem potem u agencji, kancelarii, biur rachunkowych i firm IT: dobra usługa, zero systemu jej sprzedawania. Z tych obserwacji zbudowałem jeden produkt:",
      p2strong: "strona, lejek, reklamy i plan działania co miesiąc",
      p2b: ".",
      p3: "Bez rozmywania odpowiedzialności między dział kreacji, dział mediowy i „Panią od socialu”.",
    },
    agency: {
      eyebrow: "Jak działają agencje",
      title: "Sprzedają Ci „kompleksową obsługę”.",
      p: "W praktyce: 5 osób po kawałku, nikt nie odpowiada za wynik, a Ty płacisz fakturę i czekasz na cud.",
      items: [
        "Stronę robi grafik, który nigdy w życiu niczego nie sprzedał.",
        "Reklamy prowadzi junior uczący się na Twoim budżecie.",
        "Zero AI tam, gdzie mogłoby zaoszczędzić Ci tygodnie pracy i tysiące złotych.",
      ],
    },
    solution: {
      eyebrow: "Rozwiązanie",
      titlePre: "Jeden produkt. Jeden człowiek.",
      titlePost: "tam, gdzie ma sens.",
      pillars: [
        { title: "Strona pod konwersję", body: "Nie wizytówka. Maszyna do zamiany ruchu w zapytania — z jasnym CTA i ścieżką, która działa 24/7." },
        { title: "Lejek + follow-up", body: "Formularz kwalifikujący i automatyczna sekwencja. Żaden lead nie ucieknie do konkurencji, bo nie zdążyłeś oddzwonić." },
        { title: "Reklamy pod wynik", body: "Meta i Google prowadzone pod konkretne zapytania — nie pod „zasięg”. Wsparte AI do analizy konkurencji." },
        { title: "Strategia co miesiąc", body: "Comiesięczny plan działań, KPI i iteracje. Konkret zamiast raportu z pustymi wykresami." },
      ],
    },
    process: {
      eyebrow: "Jak to działa",
      title: "Trzy kroki. Bez ceremonii.",
      steps: [
        { t: "Bezpłatny audyt (15 min)", d: "Pokazuję 3 konkretne rzeczy do poprawy w Twoim lejku — bez pitchu i bez zobowiązań." },
        { t: "Plan i wycena", d: "Zakres szyty pod Twoją firmę i model rozliczenia dopasowany do celu — dopiero na tym etapie mówimy o pieniądzach." },
        { t: "Wdrożenie i iteracje", d: "Start prac, cotygodniowe update’y, comiesięczny plan i KPI." },
      ],
    },
    pricing: {
      eyebrow: "Wycena",
      title: "Wycena po audycie, dopasowana do zakresu.",
      p1: "Nie wrzucam widełek przed rozmową, bo nie wiem jeszcze, co trzeba zrobić. Najpierw audyt, potem konkretny zakres i cena.",
      p2: "Dla firm usługowych, które chcą realnie skalować sprzedaż — nie tylko „mieć ładną stronę”.",
      step1Label: "Krok 1 — teraz",
      step1Value: "Bezpłatny audyt",
      step1Note: "15 minut, zero zobowiązań, zero opłat.",
      step2Label: "Krok 2 — po audycie",
      step2Value: "Wycena zakresu",
      step2Note: "Model do wyboru: stała współpraca albo rozliczenie prowizyjne od wyniku, bez opłaty wstępnej.",
      includedTitle: "Co wchodzi w zakres",
      included: [
        "Strona zaprojektowana pod konwersję (element lejka, nie wizytówka)",
        "Formularz kwalifikujący + automatyczna sekwencja follow-up",
        "Prowadzenie kampanii Meta / Google i zarządzanie budżetem",
        "Comiesięczny plan działań, KPI, iteracje",
        "Jeden numer telefonu, jeden człowiek do rozliczenia",
      ],
      cta: "Umów bezpłatny audyt",
    },
    faq: {
      eyebrow: "Obiekcje, które słyszę najczęściej",
      title: "Odpowiedzi bez owijania.",
      items: [
        { q: "Mam już kogoś od marketingu.", a: "Nie zastępuję nikogo na siłę. Wystarczy sprawdzić, czy to, co macie dzisiaj, daje realne liczby: koszt leada, koszt zlecenia, ROI. Jeśli tak — nie ma o czym rozmawiać. Jeśli nie — wiesz, gdzie mnie znaleźć." },
        { q: "Ile to kosztuje?", a: "Zależy od zakresu, dlatego wycenę dostajesz po bezpłatnym audycie. Możliwy jest też model prowizyjny — bez opłaty wstępnej, rozliczenie od wyniku." },
        { q: "Jak szybko zobaczę efekty?", a: "Celem jest uruchomienie całego lejka w 30–60 dni i pierwsze zapytania w tym okresie. Potem optymalizacja i skalowanie. Żadnych gwarancji z sufitu." },
        { q: "To drogo.", a: "Policz koszt braku działania i wartość jednego pozyskanego klienta dla Twojej firmy. Zwykle wychodzi na to, że pakiet spłaca się z 1–2 zleceń miesięcznie." },
      ],
    },
    finalCta: {
      titlePre: "Chcesz zobaczyć, co dokładnie",
      titleAccent: "poprawiłbym u Ciebie?",
      p: "15 minut. Za darmo. Bez zobowiązań. Wychodzisz z 3 konkretnymi rzeczami do poprawy — nawet jeśli nie zaczniemy współpracy.",
      cta1: "Zarezerwuj audyt",
      cta2: "Kalkulator",
    },
    footer: {
      tagline: "Strona, lejek, reklamy i strategia wzrostu — w jednym produkcie. Dla firm usługowych w Polsce i w Niemczech.",
      contact: "Kontakt",
      company: "Dane firmy",
      rights: "Wszystkie prawa zastrzeżone.",
      privacy: "Polityka prywatności",
      terms: "Regulamin",
      impressum: "Impressum",
    },
  },

  en: {
    meta: {
      title: "Vantix — Website, funnel, ads and growth strategy",
      description: "Growth partner for service businesses. Website, funnel, ads and a monthly strategy — one person accountable for the whole client acquisition funnel.",
    },
    nav: { problem: "Problem", solution: "Solution", process: "Process", pricing: "Pricing", audit: "Audit", blog: "Blog", menu: "Menu", theme: "Toggle theme", language: "Language" },
    hero: {
      badge: "Growth partner for service businesses",
      h1a: "You paid an agency.",
      h1b: "You still have no",
      h1c: "results",
      p: "90% of agencies don't get AI, and when something fails it's always \u201Csomeone else on the team\u201D. Here one person is accountable: me.",
      cta: "Free audit — 15 min",
      ctaNote: "No commitment. Three concrete points.",
    },
    promise: {
      eyebrow: "How I work",
      title: "A promise about the process, not about miracles.",
      items: [
        { k: "Target: 30–60 days", v: "That's usually what it takes to launch the site, the funnel and the first campaigns — up to the first inquiries." },
        { k: "1 person", v: "One contact, one invoice, one person accountable for the result. No finger-pointing." },
        { k: "Zero risk to start", v: "We start with a free audit. Scope and pricing model come after it, not before." },
      ],
    },
    story: {
      eyebrow: "Where this comes from",
      title: "Before I built funnels, I worked with my hands.",
      p1: "Installations, fit-outs, real work on site — not PowerPoint. I worked for people who were fully booked one month and had an empty pipeline the next, because acquisition relied purely on referrals.",
      p2a: "I later saw the exact same problem at agencies, law firms, accounting offices and IT companies: a good service, no system to sell it. Out of those observations I built one product:",
      p2strong: "website, funnel, ads and a monthly action plan",
      p2b: ".",
      p3: "No accountability spread across a creative team, a media team and \u201Cthe social media girl\u201D.",
    },
    agency: {
      eyebrow: "How agencies operate",
      title: "They sell you \u201Cfull-service\u201D.",
      p: "In practice: five people doing fragments, nobody accountable for the outcome, while you pay the invoice and wait for a miracle.",
      items: [
        "The website is built by a designer who has never sold anything.",
        "The ads are run by a junior learning on your budget.",
        "Zero AI where it could save you weeks of work and thousands in budget.",
      ],
    },
    solution: {
      eyebrow: "Solution",
      titlePre: "One product. One person.",
      titlePost: "where it actually helps.",
      pillars: [
        { title: "Conversion-first website", body: "Not a business card. A machine that turns traffic into inquiries — clear CTA and a path that works 24/7." },
        { title: "Funnel + follow-up", body: "A qualifying form and an automated sequence. No lead walks to a competitor because you didn't call back in time." },
        { title: "Ads built for results", body: "Meta and Google run for actual inquiries — not for \u201Creach\u201D. Backed by AI for competitor analysis." },
        { title: "Monthly strategy", body: "A monthly action plan, KPIs and iterations. Substance instead of a report full of empty charts." },
      ],
    },
    process: {
      eyebrow: "How it works",
      title: "Three steps. No ceremony.",
      steps: [
        { t: "Free audit (15 min)", d: "I show you three concrete things to fix in your funnel — no pitch, no commitment." },
        { t: "Plan and quote", d: "Scope tailored to your company and a pricing model that fits the goal — money is discussed only at this stage." },
        { t: "Build and iterate", d: "Work starts, weekly updates, a monthly plan and KPIs." },
      ],
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Pricing after the audit, matched to scope.",
      p1: "I don't throw out ranges before we talk, because I don't yet know what needs doing. Audit first, then a concrete scope and price.",
      p2: "For service businesses that want to scale sales for real — not just \u201Chave a nice website\u201D.",
      step1Label: "Step 1 — now",
      step1Value: "Free audit",
      step1Note: "15 minutes, no commitment, no fee.",
      step2Label: "Step 2 — after the audit",
      step2Value: "Scope-based quote",
      step2Note: "Your choice of model: a fixed engagement or performance-based commission with no upfront fee.",
      includedTitle: "What's included",
      included: [
        "A website designed for conversion (part of the funnel, not a business card)",
        "Qualifying form + automated follow-up sequence",
        "Meta / Google campaign management and budget control",
        "Monthly action plan, KPIs, iterations",
        "One phone number, one person accountable",
      ],
      cta: "Book the free audit",
    },
    faq: {
      eyebrow: "The objections I hear most",
      title: "Straight answers.",
      items: [
        { q: "I already have someone doing marketing.", a: "I don't replace anyone for the sake of it. Just check whether what you have today produces real numbers: cost per lead, cost per job, ROI. If it does — nothing to discuss. If it doesn't — you know where to find me." },
        { q: "What does it cost?", a: "It depends on scope, which is why you get the quote after the free audit. A commission model is also possible — no upfront fee, paid on results." },
        { q: "How fast will I see results?", a: "The target is to have the whole funnel live within 30–60 days and first inquiries in that window. Then optimisation and scaling. No guarantees pulled out of thin air." },
        { q: "That's expensive.", a: "Compare it to the cost of doing nothing and the value of one new client for your business. Usually the package pays for itself with one or two jobs a month." },
      ],
    },
    finalCta: {
      titlePre: "Want to see exactly what",
      titleAccent: "I would fix for you?",
      p: "15 minutes. Free. No commitment. You leave with three concrete things to fix — even if we never work together.",
      cta1: "Book the audit",
      cta2: "Calculator",
    },
    footer: {
      tagline: "Website, funnel, ads and growth strategy — in one product. For service businesses in Poland and Germany.",
      contact: "Contact",
      company: "Company details",
      rights: "All rights reserved.",
      privacy: "Privacy policy",
      terms: "Terms",
      impressum: "Imprint",
    },
  },

  de: {
    meta: {
      title: "Vantix — Website, Funnel, Ads und Wachstumsstrategie",
      description: "Growth Partner für Dienstleistungsunternehmen. Website, Funnel, Ads und monatliche Strategie — eine Person verantwortet den gesamten Akquise-Funnel.",
    },
    nav: { problem: "Problem", solution: "Lösung", process: "Ablauf", pricing: "Preise", audit: "Audit", blog: "Blog", menu: "Menü", theme: "Design wechseln", language: "Sprache" },
    hero: {
      badge: "Growth Partner für Dienstleistungsunternehmen",
      h1a: "Du hast eine Agentur bezahlt.",
      h1b: "Ergebnisse hast du immer noch",
      h1c: "keine",
      p: "90 % der Agenturen verstehen KI nicht, und wenn etwas nicht läuft, war es immer „jemand anderes im Team”. Bei mir verantwortet es eine Person: ich.",
      cta: "Kostenloses Audit — 15 Min.",
      ctaNote: "Keine Verpflichtung. Drei konkrete Punkte.",
    },
    promise: {
      eyebrow: "So arbeite ich",
      title: "Ein Versprechen über den Prozess, nicht über Wunder.",
      items: [
        { k: "Ziel: 30–60 Tage", v: "So lange dauert es in der Regel, Website, Funnel und die ersten Kampagnen zu starten — bis zu den ersten Anfragen." },
        { k: "1 Person", v: "Ein Ansprechpartner, eine Rechnung, eine Verantwortung für das Ergebnis. Kein Schwarzer-Peter-Spiel." },
        { k: "Kein Risiko zum Start", v: "Wir starten mit einem kostenlosen Audit. Umfang und Abrechnungsmodell kommen erst danach." },
      ],
    },
    story: {
      eyebrow: "Woher das kommt",
      title: "Bevor ich Funnels gebaut habe, habe ich körperlich gearbeitet.",
      p1: "Montagen, Installationen, echte Arbeit auf der Baustelle — kein PowerPoint. Ich habe für Leute gearbeitet, die einen Monat voll ausgebucht waren und im nächsten eine leere Pipeline hatten, weil die Akquise nur über Empfehlungen lief.",
      p2a: "Dasselbe Problem habe ich später bei Agenturen, Kanzleien, Steuerbüros und IT-Firmen gesehen: gute Leistung, kein System, sie zu verkaufen. Aus diesen Beobachtungen ist ein Produkt entstanden:",
      p2strong: "Website, Funnel, Ads und ein monatlicher Aktionsplan",
      p2b: ".",
      p3: "Ohne Verantwortung, die sich auf Kreativabteilung, Media-Team und „die Dame für Social Media” verteilt.",
    },
    agency: {
      eyebrow: "Wie Agenturen arbeiten",
      title: "Sie verkaufen dir „Full-Service”.",
      p: "In der Praxis: fünf Leute machen Bruchstücke, niemand verantwortet das Ergebnis, und du zahlst die Rechnung und wartest auf ein Wunder.",
      items: [
        "Die Website macht ein Grafiker, der noch nie etwas verkauft hat.",
        "Die Ads betreut ein Junior, der auf deinem Budget lernt.",
        "Null KI dort, wo sie dir Wochen Arbeit und Tausende Euro sparen könnte.",
      ],
    },
    solution: {
      eyebrow: "Lösung",
      titlePre: "Ein Produkt. Eine Person.",
      titlePost: "dort, wo es Sinn ergibt.",
      pillars: [
        { title: "Website für Konversion", body: "Keine Visitenkarte. Eine Maschine, die Traffic in Anfragen verwandelt — klares CTA und ein Weg, der rund um die Uhr funktioniert." },
        { title: "Funnel + Follow-up", body: "Qualifizierendes Formular und automatische Sequenz. Kein Lead geht zur Konkurrenz, weil du nicht rechtzeitig zurückgerufen hast." },
        { title: "Ads für Ergebnisse", body: "Meta und Google auf konkrete Anfragen ausgesteuert — nicht auf „Reichweite”. Unterstützt durch KI für Wettbewerbsanalysen." },
        { title: "Strategie jeden Monat", body: "Monatlicher Aktionsplan, KPIs und Iterationen. Substanz statt Report mit leeren Diagrammen." },
      ],
    },
    process: {
      eyebrow: "So läuft es",
      title: "Drei Schritte. Ohne Zeremonie.",
      steps: [
        { t: "Kostenloses Audit (15 Min.)", d: "Ich zeige dir drei konkrete Dinge, die in deinem Funnel zu verbessern sind — ohne Pitch, ohne Verpflichtung." },
        { t: "Plan und Angebot", d: "Umfang passend zu deinem Unternehmen und ein Abrechnungsmodell passend zum Ziel — über Geld sprechen wir erst hier." },
        { t: "Umsetzung und Iteration", d: "Start der Arbeiten, wöchentliche Updates, monatlicher Plan und KPIs." },
      ],
    },
    pricing: {
      eyebrow: "Preise",
      title: "Angebot nach dem Audit, passend zum Umfang.",
      p1: "Ich nenne keine Spannen vor dem Gespräch, weil ich noch nicht weiß, was zu tun ist. Erst das Audit, dann konkreter Umfang und Preis.",
      p2: "Für Dienstleistungsunternehmen, die den Vertrieb wirklich skalieren wollen — nicht nur „eine schöne Website haben”.",
      step1Label: "Schritt 1 — jetzt",
      step1Value: "Kostenloses Audit",
      step1Note: "15 Minuten, keine Verpflichtung, keine Kosten.",
      step2Label: "Schritt 2 — nach dem Audit",
      step2Value: "Angebot nach Umfang",
      step2Note: "Modell zur Wahl: feste Zusammenarbeit oder erfolgsbasierte Provision ohne Vorabkosten.",
      includedTitle: "Was enthalten ist",
      included: [
        "Website, gestaltet für Konversion (Teil des Funnels, keine Visitenkarte)",
        "Qualifizierendes Formular + automatische Follow-up-Sequenz",
        "Betreuung von Meta-/Google-Kampagnen und Budgetsteuerung",
        "Monatlicher Aktionsplan, KPIs, Iterationen",
        "Eine Telefonnummer, eine verantwortliche Person",
      ],
      cta: "Kostenloses Audit buchen",
    },
    faq: {
      eyebrow: "Die häufigsten Einwände",
      title: "Antworten ohne Umschweife.",
      items: [
        { q: "Ich habe schon jemanden für Marketing.", a: "Ich ersetze niemanden um jeden Preis. Prüfe einfach, ob das Bestehende echte Zahlen liefert: Kosten pro Lead, Kosten pro Auftrag, ROI. Wenn ja — kein Thema. Wenn nein — du weißt, wo du mich findest." },
        { q: "Was kostet das?", a: "Das hängt vom Umfang ab, deshalb bekommst du das Angebot nach dem kostenlosen Audit. Ein Provisionsmodell ist ebenfalls möglich — ohne Vorabkosten, Abrechnung nach Ergebnis." },
        { q: "Wie schnell sehe ich Ergebnisse?", a: "Das Ziel: der komplette Funnel live in 30–60 Tagen und erste Anfragen in diesem Zeitraum. Danach Optimierung und Skalierung. Keine Garantien aus der Luft." },
        { q: "Das ist teuer.", a: "Rechne die Kosten des Nichtstuns und den Wert eines neuen Kunden für dein Unternehmen gegen. Meist rechnet sich das Paket mit einem bis zwei Aufträgen im Monat." },
      ],
    },
    finalCta: {
      titlePre: "Willst du sehen, was genau",
      titleAccent: "ich bei dir verbessern würde?",
      p: "15 Minuten. Kostenlos. Ohne Verpflichtung. Du gehst mit drei konkreten Punkten raus — auch wenn wir nie zusammenarbeiten.",
      cta1: "Audit buchen",
      cta2: "Rechner",
    },
    footer: {
      tagline: "Website, Funnel, Ads und Wachstumsstrategie — in einem Produkt. Für Dienstleistungsunternehmen in Polen und Deutschland.",
      contact: "Kontakt",
      company: "Firmendaten",
      rights: "Alle Rechte vorbehalten.",
      privacy: "Datenschutzerklärung",
      terms: "AGB",
      impressum: "Impressum",
    },
  },
} as const;
